---

- name: docker compose inetsim
  become_user: "{{ cuckoo_user }}"
  block:
  - name: ensures {{ download_dir }}/inetsim dir exists
    file: path="{{ download_dir }}/inetsim" state=directory
  - name: copy docker-compose.yml file
    template:
      src: "{{ role_path }}/files/docker-compose.yml"
      dest: "{{ download_dir }}/inetsim"
      owner: "{{ cuckoo_user }}"
      group: "{{ cuckoo_user }}"
      backup: yes
  - name: docker-compose up
    shell: |
      set timeout 3m
      docker-compose down
      sleep 2
      nohup docker-compose up -d >/dev/null 2>&1 &
    args:
      chdir: "{{ download_dir }}/inetsim"
      executable: "/bin/bash"
