---

- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add repo to sources.list apt
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    state: present
    update_cache: yes
    filename: docker

- name: install docker using apt
  sudo: yes
  package:
      name: "{{ item }}"
      state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
  register: pkg_status
  failed_when: pkg_status is failed

- name: add current user to the docker group
  become: yes
  user: name={{ cuckoo_user }} groups=docker append=yes

- name: reset ssh connection to allow user changes to affect current login user
  meta: reset_connection
