---

# Requested package manager apt was not usable by this module: 'APT' object has
# no attribute '_cache'
#- name: Gather the rpm package facts
#  package_facts:
#    manager: apt
#    strategy: all

#- name: Print the rpm package facts
#  debug:
#    var: ansible_facts.packages

- name: check if qemu installed currently
  command: "dpkg-query -W qemu-3.1.0"
  ignore_errors: true
  register: installed_package

- name: patch and install qemu
  sudo: yes
  block:
      - name: copy script to server
        copy: 
          src: "{{ role_path  }}/files/qemu-patch.sh"
          dest: /tmp/
          mode: 0755
      - name: execute the script
        command: /tmp/qemu-patch.sh qemu
        register: result
        failed_when: '"Patched" not in result.stdout'
  when: installed_package is failed

- name: install kvm/libvirt using apt
  sudo: yes
  apt:
      pkg:
        - libvirt-bin
        - virtinst
        - virt-manager
        - libvirt-dev
        - bridge-utils
        - cpu-checker
      state: latest
      dpkg_options: 'force-overwrite'
  register: pkg_status
  failed_when: pkg_status is failed

# configure kvm groups and iface
- name: check if kvm drivers installed successfully
  stat:
    path: "/dev/{{ item }}"
  with_items:
   - kvm
  register: result

- name: pip | install python package dependencies
  become_user: "{{ cuckoo_user }}"
  pip:
      name: libvirt-python
      state: present
      virtualenv: "{{ cuckoo_virtenv }}"
      virtualenv_command: virtualenv
      virtualenv_python: python2.7
  register: pkg_status
  failed_when: pkg_status is failed

- name: append cuckoo user to libvirtd and kvm groups
  become: yes
  user:
    name: "{{ cuckoo_user }}"
    shell: /bin/bash
    groups: libvirtd, kvm
    append: yes

- name: reset ssh connection to allow user changes to affect current login user
  meta: reset_connection

- name: setup libvirtd unix ro/rw permissions
  replace:
    path: "{{ libvirt_conf }}"
    regexp: '{{ item.regex }}'
    replace: '{{ item.replace }}'
    owner: root
    group: root
  with_items:
    - { regex: '#unix_sock_group', replace: 'unix_sock_group' }
    - { regex: '#unix_sock_ro_perms = "0777"', replace: 'unix_sock_ro_perms = "0770"' }
    - { regex:  '#unix_sock_rw_perms = "0770"', replace: 'unix_sock_rw_perms = "0770"'}
    - { regex:  '#auth_unix_ro = "none"', replace: 'auth_unix_ro = "none"'}
    - { regex:  '#auth_unix_rw = "none"', replace: 'auth_unix_rw = "none"'}

- name: configuring apparmor for libvirtd
  block:
    - name: setup user/group qemu.conf
      replace:
        path: "{{ qemu_conf }}"
        regexp: '{{ item.regex }}'
        replace: '{{ item.replace }}'
        owner: root
        group: root
      with_items:
        - { regex: '#user = "root"', replace: 'user = "{{ cuckoo_user }}"' }
        - { regex: '#group = "root"', replace: 'group = "libvirtd"' }
        - { regex: '#security_driver = "selinux"', replace: 'security_driver = "none"' }
    - name: disable apparmor for libvirtd
      command: aa-disable /usr/sbin/libvirtd
      ignore_errors: yes

- name: configure kvm iface
  sudo: yes
  block:
    - name: configuring dhcp kvm default iface
      replace:
        path: "{{ network_conf }}"
        regexp: '{{ item.regex }}'
        replace: '{{ item.replace }}'
        owner: root
        group: root
      with_items:
        - { regex: "<bridge name=\'\\w+\'", replace: "<bridge name=\'{{ kvm_iface }}\'" }
        - { regex: "<ip address=\'\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\'", replace: "<ip address=\'{{ kvm_bridge_gw }}\'" }
        - { regex: "<range start=\'\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\\.\\d{1,3}\'", replace: "<range start=\'{{ kvm_range_start }}\'" }
    - name: check if {{ kvm_iface }} exists
      ignore_errors: true
      changed_when: false
      command: ifconfig "{{ kvm_iface }}"
      register: iface
    - name: ifdown & start default network 
      command: "{{ item }}"
      with_items:
        - "virsh net-destroy default"
        - "virsh net-start default"
      when: iface is succeeded
