
---

- name: check if vmrun exists
  stat:
    path: "{{ VMWare_PATH }}"
  register: vmrun

- name: install VMWare Workstation
  become: yes
  block:
    - get_url:
        url: "{{ VMWare_URL }}"
        dest: "/tmp/vmware.bundle"
        checksum: "md5:{{ VMWare_md5sum }}"
        # https://communities.vmware.com/thread/564106
    - shell: |
        set timeout 3m
        chmod +x ./vmware.bundle
        yes '' | ./vmware.bundle -s vmware-workstation serialNumber "N0233-XZK44-J8JDE-0JCHH-CE4HN" --console --eulas-agreed
      args:
        chdir: "/tmp"
        executable: "/bin/bash"
      register: result
      when: "'successful' in result.stdout"
    - debug:
        var: result
  when: vmrun.stat.exists == False
